#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

mkdir -p "$PLUSHU_ROOT/nginx/http"

# Write some sensible SSL configuration directives
if [[ ! -f "$PLUSHU_ROOT/nginx/http/ssl.conf" ]]; then
  cat > "$PLUSHU_ROOT/nginx/http/ssl.conf" <<EOF
ssl_session_cache shared:SSL:20m;
ssl_session_timeout 10m;

ssl_ciphers EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;
ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
ssl_prefer_server_ciphers on;
EOF
fi

if [[ "$EUID" == 0 ]]; then
  chown -R "$PLUSHU_USER:" "$PLUSHU_ROOT/nginx/http"
fi
